name: Branch-relative badges
description: Adds badges with branch link to README.md.tpl
inputs:
  badges:
    required: true
    description: "JSON array of [{ \"name\": '<badge name>', yaml: '<name of the yaml>' }]"
  context:
    required: true
    desription: JSONified github context
  domain:
    description: Domain of the github repo
    default: 'https://github.com'
  template:
    required: false
    default: 'README.md.tpl'
    description: "Template for README.md"
runs:
  using: 'node16'
  main: 'index.js'
