
name: Dependecy graph

on:
  push:
    branches: [ 'master' ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
