on:
  pull_request:
    types:
    - reopened
    - opened
    - edited
    - synchronize

name: Merge steward pr

jobs:
  merge:
    name: Merge scala steward pr
    runs-on: ubuntu-latest
    if: contains(github.ref, 'update/')
    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Compile & Test'
        repo-token: ${{ secrets.MERGE_TOKEN }}
        wait-interval: 10
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
      with:
        MERGE_METHOD: squash
        ALLOWED_UPDATE: minor
        GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

