
version: 2
name: Scala Steward Github Action
jobs:
  # You may pin to the exact commit or the version.
  uses: scala-steward-org/scala-steward-action@v2.23.0
  with:
    # Author name to use in commits
    author-name: Scala Steward# optional
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '32 0 * * 0'
